<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FirebaseAdmin" Version="3.1.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.7.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.5" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.17.3" />
    <PackageReference Include="Stripe.net" Version="49.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinTechAPI.Domain\FinTechAPI.Domain.csproj" />
    <ProjectReference Include="..\FinTechAPI.Application\FinTechAPI.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ML\Models\*.onnx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
