import { useEffect, useState, useCallback } from "react";
import {
  AlertTriangle,
  Bell,
  CheckCircle,
  Info,
  RefreshCw,
  X,
} from "lucide-react";
import {
  getSystemAlerts,
  dismissSystemAlert,
  type ApiSystemAlert,
} from "../api/client";

function SeverityIcon({ severity }: { severity: string }) {
  if (severity === "critical") return <AlertTriangle className="w-4 h-4 text-destructive flex-shrink-0" />;
  if (severity === "warning") return <AlertTriangle className="w-4 h-4 text-yellow-500 flex-shrink-0" />;
  return <Info className="w-4 h-4 text-accent flex-shrink-0" />;
}

function severityBorder(severity: string) {
  if (severity === "critical") return "border-destructive/30 bg-destructive/5";
  if (severity === "warning") return "border-yellow-500/30 bg-yellow-500/5";
  return "border-accent/20 bg-accent/5";
}

function severityLabel(severity: string) {
  const cls =
    severity === "critical"
      ? "bg-destructive/10 text-destructive"
      : severity === "warning"
        ? "bg-yellow-500/10 text-yellow-600"
        : "bg-accent/10 text-accent";
  return (
    <span className={`px-2 py-0.5 rounded-full text-[11px] font-semibold uppercase tracking-wide ${cls}`}>
      {severity}
    </span>
  );
}

function timeAgo(dateStr: string): string {
  const seconds = Math.floor((Date.now() - new Date(dateStr).getTime()) / 1000);
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return new Date(dateStr).toLocaleDateString();
}

export function SystemAlerts() {
  const [alerts, setAlerts] = useState<ApiSystemAlert[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [dismissingId, setDismissingId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getSystemAlerts(100);
      setAlerts(data);
    } catch {
      setError("Failed to load system alerts.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const handleDismiss = async (alertId: string) => {
    setDismissingId(alertId);
    try {
      await dismissSystemAlert(alertId);
      setAlerts((prev) => prev.filter((a) => a.id !== alertId));
    } catch {
      // silent — user can retry
    } finally {
      setDismissingId(null);
    }
  };

  const criticalCount = alerts.filter((a) => a.severity === "critical").length;
  const warningCount = alerts.filter((a) => a.severity === "warning").length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Bell className="w-6 h-6 text-accent" />
          <div>
            <h1 className="text-2xl font-semibold text-foreground">
              System Alerts
            </h1>
            <p className="text-sm text-muted-foreground">
              Operational alerts generated by background services.
            </p>
          </div>
        </div>
        <button
          onClick={load}
          disabled={loading}
          className="flex items-center gap-2 px-4 py-2 text-sm border border-border rounded-lg hover:bg-secondary transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </button>
      </div>

      {error && (
        <div className="bg-destructive/10 border border-destructive/30 text-destructive text-sm rounded-lg px-4 py-3">
          {error}
        </div>
      )}

      {/* Summary bar */}
      {!loading && alerts.length > 0 && (
        <div className="flex gap-4 flex-wrap">
          {criticalCount > 0 && (
            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-destructive/10 border border-destructive/30">
              <AlertTriangle className="w-4 h-4 text-destructive" />
              <span className="text-sm font-medium text-destructive">
                {criticalCount} critical
              </span>
            </div>
          )}
          {warningCount > 0 && (
            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-yellow-500/10 border border-yellow-500/30">
              <AlertTriangle className="w-4 h-4 text-yellow-600" />
              <span className="text-sm font-medium text-yellow-600">
                {warningCount} warning
              </span>
            </div>
          )}
          <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-secondary border border-border">
            <Bell className="w-4 h-4 text-muted-foreground" />
            <span className="text-sm text-muted-foreground">
              {alerts.length} total active
            </span>
          </div>
        </div>
      )}

      {/* Alerts list */}
      {loading ? (
        <div className="space-y-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <div
              key={i}
              className="animate-pulse h-20 bg-secondary rounded-lg border border-border"
            />
          ))}
        </div>
      ) : alerts.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-muted-foreground bg-card border border-border rounded-lg">
          <CheckCircle className="w-10 h-10 mb-3 text-success opacity-60" />
          <p className="text-sm font-medium">All clear!</p>
          <p className="text-xs mt-1">No active system alerts.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {alerts.map((alert) => (
            <div
              key={alert.id}
              className={`border rounded-lg px-4 py-4 flex items-start gap-3 ${severityBorder(alert.severity)}`}
            >
              <SeverityIcon severity={alert.severity} />

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1 flex-wrap">
                  <p className="text-sm font-medium text-foreground">
                    {alert.title}
                  </p>
                  {severityLabel(alert.severity)}
                  <span className="text-xs text-muted-foreground ml-auto">
                    {timeAgo(alert.createdAt)}
                  </span>
                </div>
                <p className="text-sm text-muted-foreground">{alert.message}</p>
                {(alert.entityType || alert.entityId) && (
                  <p className="text-xs text-muted-foreground/70 mt-1 font-mono">
                    {alert.entityType}/{alert.entityId}
                  </p>
                )}
              </div>

              <button
                onClick={() => handleDismiss(alert.id)}
                disabled={dismissingId === alert.id}
                title="Dismiss alert"
                className="flex-shrink-0 p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors disabled:opacity-50"
              >
                {dismissingId === alert.id ? (
                  <RefreshCw className="w-4 h-4 animate-spin" />
                ) : (
                  <X className="w-4 h-4" />
                )}
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

